// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "amber" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "amber"
    readonly property string label:     "Amber"
    readonly property string group:     "Terminal"
    readonly property string glyph:     "◈"
    readonly property bool   dark:      true

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#100c04"
    readonly property color surface:      "#171106"
    readonly property color fg:           "#ffb000"
    readonly property color muted:        "#cc8c00"
    readonly property color faint:        "#a8760c"
    readonly property color border:       "#4a3608"
    readonly property color borderSubtle: "#33250a"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#ffcf5e"
    readonly property color accentHover: "#ffe08a"
    readonly property color code:        "#ffe9b0"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#edaf1f"
    readonly property color orange: "#efb93b"
    readonly property color yellow: "#f1c252"
    readonly property color green:  "#f3ca6a"
    readonly property color cyan:   "#f5d282"
    readonly property color blue:   "#f7db99"
    readonly property color purple: "#f9e3b1"
    readonly property color pink:   "#fbecc8"
}
