// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "amber-light" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "amber-light"
    readonly property string label:     "Amber Light"
    readonly property string group:     "Terminal"
    readonly property string glyph:     "◈"
    readonly property bool   dark:      false

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#f9f3e7"
    readonly property color surface:      "#f3e8d3"
    readonly property color fg:           "#4d3605"
    readonly property color muted:        "#c0870c"
    readonly property color faint:        "#efae24"
    readonly property color border:       "#f1ce7e"
    readonly property color borderSubtle: "#f0dbb2"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#906709"
    readonly property color accentHover: "#866509"
    readonly property color code:        "#866309"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#8e660b"
    readonly property color orange: "#8e660b"
    readonly property color yellow: "#8e670b"
    readonly property color green:  "#8e670b"
    readonly property color cyan:   "#8e660b"
    readonly property color blue:   "#8e670b"
    readonly property color purple: "#8e660b"
    readonly property color pink:   "#8f680b"
}
