// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "ayu-light" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "ayu-light"
    readonly property string label:     "Ayu Light"
    readonly property string group:     "Editor"
    readonly property string glyph:     "⟡"
    readonly property bool   dark:      false

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#ebeef4"
    readonly property color surface:      "#dbe1eb"
    readonly property color fg:           "#342f1d"
    readonly property color muted:        "#837449"
    readonly property color faint:        "#697dab"
    readonly property color border:       "#a4b4cc"
    readonly property color borderSubtle: "#c4cfde"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#866013"
    readonly property color accentHover: "#906109"
    readonly property color code:        "#577619"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#c2141e"
    readonly property color orange: "#ac4e0b"
    readonly property color yellow: "#866013"
    readonly property color green:  "#567619"
    readonly property color cyan:   "#1b7356"
    readonly property color blue:   "#0b71ac"
    readonly property color purple: "#6a0dc9"
    readonly property color pink:   "#c2141e"
}
