// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "ayu" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "ayu"
    readonly property string label:     "Ayu"
    readonly property string group:     "Editor"
    readonly property string glyph:     "⟡"
    readonly property bool   dark:      true

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#0b0e14"
    readonly property color surface:      "#0f131a"
    readonly property color fg:           "#bfbdb6"
    readonly property color muted:        "#8a8986"
    readonly property color faint:        "#565b66"
    readonly property color border:       "#1d2229"
    readonly property color borderSubtle: "#151a21"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#e6b450"
    readonly property color accentHover: "#ffcb6b"
    readonly property color code:        "#aad94c"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#f07178"
    readonly property color orange: "#ff8f40"
    readonly property color yellow: "#e6b450"
    readonly property color green:  "#aad94c"
    readonly property color cyan:   "#95e6cb"
    readonly property color blue:   "#59c2ff"
    readonly property color purple: "#d2a6ff"
    readonly property color pink:   "#f07178"
}
