// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "blueprint" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "blueprint"
    readonly property string label:     "Blueprint"
    readonly property string group:     "Light & print"
    readonly property string glyph:     "⊟"
    readonly property bool   dark:      true

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#0d3b66"
    readonly property color surface:      "#124a7d"
    readonly property color fg:           "#eaf3ff"
    readonly property color muted:        "#bcd6ef"
    readonly property color faint:        "#96bade"
    readonly property color border:       "#2f6ba0"
    readonly property color borderSubtle: "#1a5286"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#8bd8ff"
    readonly property color accentHover: "#b3e6ff"
    readonly property color code:        "#d3eaff"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#2faeee"
    readonly property color orange: "#4cb9f0"
    readonly property color yellow: "#63c2f2"
    readonly property color green:  "#7bcbf4"
    readonly property color cyan:   "#92d5f6"
    readonly property color blue:   "#aadef8"
    readonly property color purple: "#c2e7fa"
    readonly property color pink:   "#d9f0fc"
}
