// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "c64-light" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "c64-light"
    readonly property string label:     "Commodore Light"
    readonly property string group:     "Retro"
    readonly property string glyph:     "▩"
    readonly property bool   dark:      false

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#e8e7f9"
    readonly property color surface:      "#d6d3f3"
    readonly property color fg:           "#0f054d"
    readonly property color muted:        "#301bb1"
    readonly property color faint:        "#5c4aca"
    readonly property color border:       "#a099d7"
    readonly property color borderSubtle: "#bfbae8"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#096e86"
    readonly property color accentHover: "#096f86"
    readonly property color code:        "#127308"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#0b6d84"
    readonly property color orange: "#0b6c84"
    readonly property color yellow: "#0b6d84"
    readonly property color green:  "#0b6d84"
    readonly property color cyan:   "#0b6d84"
    readonly property color blue:   "#0b6d84"
    readonly property color purple: "#0b6c84"
    readonly property color pink:   "#0b6c84"
}
