// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "c64" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "c64"
    readonly property string label:     "Commodore"
    readonly property string group:     "Retro"
    readonly property string glyph:     "▩"
    readonly property bool   dark:      true

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#1f1860"
    readonly property color surface:      "#2b227e"
    readonly property color fg:           "#c3b9ff"
    readonly property color muted:        "#9d90ee"
    readonly property color faint:        "#9a8fde"
    readonly property color border:       "#4a3fa0"
    readonly property color borderSubtle: "#362c85"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#8be9ff"
    readonly property color accentHover: "#b3f1ff"
    readonly property color code:        "#a6ff9c"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#2fcaee"
    readonly property color orange: "#4cd1f0"
    readonly property color yellow: "#63d7f2"
    readonly property color green:  "#7bddf4"
    readonly property color cyan:   "#92e3f6"
    readonly property color blue:   "#aae9f8"
    readonly property color purple: "#c2effa"
    readonly property color pink:   "#d9f5fc"
}
