// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "catppuccin-latte" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "catppuccin-latte"
    readonly property string label:     "Catppuccin Latte"
    readonly property string group:     "Modern"
    readonly property string glyph:     "○"
    readonly property bool   dark:      false

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#eff1f5"
    readonly property color surface:      "#e6e9ef"
    readonly property color fg:           "#4c4f69"
    readonly property color muted:        "#6c6f85"
    readonly property color faint:        "#9ca0b0"
    readonly property color border:       "#ccd0da"
    readonly property color borderSubtle: "#dce0e8"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#8839ef"
    readonly property color accentHover: "#7025d0"
    readonly property color code:        "#40a02b"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#d20f39"
    readonly property color orange: "#fe640b"
    readonly property color yellow: "#df8e1d"
    readonly property color green:  "#40a02b"
    readonly property color cyan:   "#04a5e5"
    readonly property color blue:   "#1e66f5"
    readonly property color purple: "#8839ef"
    readonly property color pink:   "#ea76cb"
}
