// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "catppuccin-mocha" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "catppuccin-mocha"
    readonly property string label:     "Catppuccin Mocha"
    readonly property string group:     "Modern"
    readonly property string glyph:     "●"
    readonly property bool   dark:      true

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#1e1e2e"
    readonly property color surface:      "#181825"
    readonly property color fg:           "#cdd6f4"
    readonly property color muted:        "#a6adc8"
    readonly property color faint:        "#6c7086"
    readonly property color border:       "#313244"
    readonly property color borderSubtle: "#252537"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#cba6f7"
    readonly property color accentHover: "#dcc0ff"
    readonly property color code:        "#a6e3a1"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#f38ba8"
    readonly property color orange: "#fab387"
    readonly property color yellow: "#f9e2af"
    readonly property color green:  "#a6e3a1"
    readonly property color cyan:   "#89dceb"
    readonly property color blue:   "#89b4fa"
    readonly property color purple: "#cba6f7"
    readonly property color pink:   "#f5c2e7"
}
