// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "catppuccin-frappe" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "catppuccin-frappe"
    readonly property string label:     "Catppuccin Frappé"
    readonly property string group:     "Modern"
    readonly property string glyph:     "◑"
    readonly property bool   dark:      true

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#303446"
    readonly property color surface:      "#292c3c"
    readonly property color fg:           "#c6d0f5"
    readonly property color muted:        "#a5adce"
    readonly property color faint:        "#737994"
    readonly property color border:       "#414559"
    readonly property color borderSubtle: "#353849"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#ca9ee6"
    readonly property color accentHover: "#dbb2f5"
    readonly property color code:        "#a6d189"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#e78284"
    readonly property color orange: "#ef9f76"
    readonly property color yellow: "#e5c890"
    readonly property color green:  "#a6d189"
    readonly property color cyan:   "#99d1db"
    readonly property color blue:   "#8caaee"
    readonly property color purple: "#ca9ee6"
    readonly property color pink:   "#f4b8e4"
}
