// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "catppuccin-macchiato" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "catppuccin-macchiato"
    readonly property string label:     "Catppuccin Macchiato"
    readonly property string group:     "Modern"
    readonly property string glyph:     "◕"
    readonly property bool   dark:      true

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#24273a"
    readonly property color surface:      "#1e2030"
    readonly property color fg:           "#cad3f5"
    readonly property color muted:        "#a5adcb"
    readonly property color faint:        "#6e738d"
    readonly property color border:       "#363a4f"
    readonly property color borderSubtle: "#2b2e40"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#c6a0f6"
    readonly property color accentHover: "#d7b8ff"
    readonly property color code:        "#a6da95"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#ed8796"
    readonly property color orange: "#f5a97f"
    readonly property color yellow: "#eed49f"
    readonly property color green:  "#a6da95"
    readonly property color cyan:   "#91d7e3"
    readonly property color blue:   "#8aadf4"
    readonly property color purple: "#c6a0f6"
    readonly property color pink:   "#f5bde6"
}
