// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "cloud" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "cloud"
    readonly property string label:     "Cloud"
    readonly property string group:     "Light & print"
    readonly property string glyph:     "☁"
    readonly property bool   dark:      false

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#f3f6fb"
    readonly property color surface:      "#e7edf5"
    readonly property color fg:           "#273243"
    readonly property color muted:        "#56657a"
    readonly property color faint:        "#5d6c83"
    readonly property color border:       "#cad4e2"
    readonly property color borderSubtle: "#dce3ec"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#5369a8"
    readonly property color accentHover: "#43568f"
    readonly property color code:        "#3c6e71"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#a63f3f"
    readonly property color orange: "#a66f3f"
    readonly property color yellow: "#a6953f"
    readonly property color green:  "#3fa650"
    readonly property color cyan:   "#3fa6a6"
    readonly property color blue:   "#3f6aa6"
    readonly property color purple: "#763fa6"
    readonly property color pink:   "#a63f81"
}
