// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "creature" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "creature"
    readonly property string label:     "The Creature"
    readonly property string group:     "Horror"
    readonly property string glyph:     "≋"
    readonly property bool   dark:      true

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#081515"
    readonly property color surface:      "#0e2523"
    readonly property color fg:           "#c7eee5"
    readonly property color muted:        "#83b9b0"
    readonly property color faint:        "#4e817b"
    readonly property color border:       "#1e5952"
    readonly property color borderSubtle: "#123b37"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#54d6bf"
    readonly property color accentHover: "#82ebd8"
    readonly property color code:        "#9be36f"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#dd6868"
    readonly property color orange: "#d9945e"
    readonly property color yellow: "#d5d56b"
    readonly property color green:  "#7fd18e"
    readonly property color cyan:   "#54d6bf"
    readonly property color blue:   "#70a8cf"
    readonly property color purple: "#a28bc5"
    readonly property color pink:   "#cd80a5"
}
