// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "creature-light" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "creature-light"
    readonly property string label:     "The Creature Light"
    readonly property string group:     "Horror"
    readonly property string glyph:     "≋"
    readonly property bool   dark:      false

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#e9f7f7"
    readonly property color surface:      "#d6f0ed"
    readonly property color fg:           "#133f35"
    readonly property color muted:        "#498379"
    readonly property color faint:        "#69aba3"
    readonly property color border:       "#94dbd3"
    readonly property color borderSubtle: "#b9eae5"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#1d7c6a"
    readonly property color accentHover: "#147b68"
    readonly property color code:        "#3c7718"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#af2727"
    readonly property color orange: "#a55e27"
    readonly property color yellow: "#6f6f1f"
    readonly property color green:  "#2e7f3c"
    readonly property color cyan:   "#1d7c6b"
    readonly property color blue:   "#3675a0"
    readonly property color purple: "#64478f"
    readonly property color pink:   "#9a3d69"
}
