// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "crt-light" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "crt-light"
    readonly property string label:     "CRT Light"
    readonly property string group:     "Terminal"
    readonly property string glyph:     "▦"
    readonly property bool   dark:      false

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#ebf4eb"
    readonly property color surface:      "#dbebdb"
    readonly property color fg:           "#054d14"
    readonly property color muted:        "#28a445"
    readonly property color faint:        "#44d067"
    readonly property color border:       "#97d8a8"
    readonly property color borderSubtle: "#bbe7c3"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#087d28"
    readonly property color accentHover: "#087c25"
    readonly property color code:        "#397d08"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#0a7b29"
    readonly property color orange: "#0b7b28"
    readonly property color yellow: "#0a7b29"
    readonly property color green:  "#0a7b29"
    readonly property color cyan:   "#0a7b28"
    readonly property color blue:   "#0a7b28"
    readonly property color purple: "#0a7b28"
    readonly property color pink:   "#0a7b2a"
}
