// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "crt" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "crt"
    readonly property string label:     "CRT"
    readonly property string group:     "Terminal"
    readonly property string glyph:     "▦"
    readonly property bool   dark:      true

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#0a0e0a"
    readonly property color surface:      "#0f150f"
    readonly property color fg:           "#4afa6e"
    readonly property color muted:        "#2fbf50"
    readonly property color faint:        "#279a44"
    readonly property color border:       "#1c4a28"
    readonly property color borderSubtle: "#133619"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#7dffa0"
    readonly property color accentHover: "#b0ffc4"
    readonly property color code:        "#9dff57"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#2fee63"
    readonly property color orange: "#4cf078"
    readonly property color yellow: "#63f28a"
    readonly property color green:  "#7bf49c"
    readonly property color cyan:   "#92f6ad"
    readonly property color blue:   "#aaf8bf"
    readonly property color purple: "#c2fad1"
    readonly property color pink:   "#d9fce3"
}
