// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "cyberpunk" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "cyberpunk"
    readonly property string label:     "Cyberpunk"
    readonly property string group:     "Neon"
    readonly property string glyph:     "⌖"
    readonly property bool   dark:      true

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#0a0a0f"
    readonly property color surface:      "#13131f"
    readonly property color fg:           "#f0f0ff"
    readonly property color muted:        "#b2b2d4"
    readonly property color faint:        "#7c7ca6"
    readonly property color border:       "#2a2a45"
    readonly property color borderSubtle: "#18182a"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#fcee0a"
    readonly property color accentHover: "#fff45c"
    readonly property color code:        "#00f0ff"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#ee2b2b"
    readonly property color orange: "#ee862b"
    readonly property color yellow: "#eecd2b"
    readonly property color green:  "#2bee4b"
    readonly property color cyan:   "#2beeee"
    readonly property color blue:   "#2b7cee"
    readonly property color purple: "#932bee"
    readonly property color pink:   "#ee2ba6"
}
