// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "cyberpunk-light" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "cyberpunk-light"
    readonly property string label:     "Cyberpunk Light"
    readonly property string group:     "Neon"
    readonly property string glyph:     "⌖"
    readonly property bool   dark:      false

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#ebebf4"
    readonly property color surface:      "#dbdbeb"
    readonly property color fg:           "#05054d"
    readonly property color muted:        "#494983"
    readonly property color faint:        "#6969ab"
    readonly property color border:       "#a4a4cc"
    readonly property color borderSubtle: "#c4c4de"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#736c07"
    readonly property color accentHover: "#736c08"
    readonly property color code:        "#08767d"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#c61010"
    readonly property color orange: "#a0520d"
    readonly property color yellow: "#7b670a"
    readonly property color green:  "#0a7b1d"
    readonly property color cyan:   "#097171"
    readonly property color blue:   "#105cc6"
    readonly property color purple: "#7110c6"
    readonly property color pink:   "#c61083"
}
