// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "dawn" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "dawn"
    readonly property string label:     "Dawn"
    readonly property string group:     "Light & print"
    readonly property string glyph:     "◒"
    readonly property bool   dark:      false

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#fff7f1"
    readonly property color surface:      "#f5e9e1"
    readonly property color fg:           "#3b302f"
    readonly property color muted:        "#6f5a56"
    readonly property color faint:        "#75615d"
    readonly property color border:       "#dec9bf"
    readonly property color borderSubtle: "#eadbd3"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#9a4f72"
    readonly property color accentHover: "#7d3b59"
    readonly property color code:        "#486b58"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#a63f3f"
    readonly property color orange: "#a66f3f"
    readonly property color yellow: "#a6953f"
    readonly property color green:  "#3fa650"
    readonly property color cyan:   "#3fa6a6"
    readonly property color blue:   "#3f6aa6"
    readonly property color purple: "#763fa6"
    readonly property color pink:   "#a63f81"
}
