// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "dracula-light" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "dracula-light"
    readonly property string label:     "Dracula Light"
    readonly property string group:     "Editor"
    readonly property string glyph:     "✦"
    readonly property bool   dark:      false

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#ebedf4"
    readonly property color surface:      "#dbddeb"
    readonly property color fg:           "#35351d"
    readonly property color muted:        "#495583"
    readonly property color faint:        "#6978ab"
    readonly property color border:       "#a4a9cc"
    readonly property color borderSubtle: "#c4c8de"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#560cc0"
    readonly property color accentHover: "#460a99"
    readonly property color code:        "#087d26"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#c90d0d"
    readonly property color orange: "#99540a"
    readonly property color yellow: "#626907"
    readonly property color green:  "#087d26"
    readonly property color cyan:   "#097086"
    readonly property color blue:   "#4d5c89"
    readonly property color purple: "#5a0dc9"
    readonly property color pink:   "#c90d79"
}
