// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "dracula" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "dracula"
    readonly property string label:     "Dracula"
    readonly property string group:     "Editor"
    readonly property string glyph:     "✦"
    readonly property bool   dark:      true

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#282a36"
    readonly property color surface:      "#21222c"
    readonly property color fg:           "#f8f8f2"
    readonly property color muted:        "#a9aec2"
    readonly property color faint:        "#8f96ad"
    readonly property color border:       "#44475a"
    readonly property color borderSubtle: "#383a47"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#bd93f9"
    readonly property color accentHover: "#cba5ff"
    readonly property color code:        "#50fa7b"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#ff5555"
    readonly property color orange: "#ffb86c"
    readonly property color yellow: "#f1fa8c"
    readonly property color green:  "#50fa7b"
    readonly property color cyan:   "#8be9fd"
    readonly property color blue:   "#6272a4"
    readonly property color purple: "#bd93f9"
    readonly property color pink:   "#ff79c6"
}
