// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "everforest" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "everforest"
    readonly property string label:     "Everforest"
    readonly property string group:     "Modern"
    readonly property string glyph:     "❦"
    readonly property bool   dark:      true

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#2d353b"
    readonly property color surface:      "#343f44"
    readonly property color fg:           "#d3c6aa"
    readonly property color muted:        "#9da9a0"
    readonly property color faint:        "#859289"
    readonly property color border:       "#3d484d"
    readonly property color borderSubtle: "#343f44"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#a7c080"
    readonly property color accentHover: "#bdd4a0"
    readonly property color code:        "#83c092"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#e67e80"
    readonly property color orange: "#e69875"
    readonly property color yellow: "#dbbc7f"
    readonly property color green:  "#a7c080"
    readonly property color cyan:   "#83c092"
    readonly property color blue:   "#7fbbb3"
    readonly property color purple: "#d699b6"
    readonly property color pink:   "#d699b6"
}
