// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "everforest-light" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "everforest-light"
    readonly property string label:     "Everforest Light"
    readonly property string group:     "Modern"
    readonly property string glyph:     "❦"
    readonly property bool   dark:      false

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#ebf0f4"
    readonly property color surface:      "#dbe6eb"
    readonly property color fg:           "#362e1c"
    readonly property color muted:        "#498358"
    readonly property color faint:        "#69ab7d"
    readonly property color border:       "#a4bfcc"
    readonly property color borderSubtle: "#c4d6de"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#5e743a"
    readonly property color accentHover: "#557033"
    readonly property color code:        "#3a7348"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#b32326"
    readonly property color orange: "#ad4b1f"
    readonly property color yellow: "#876726"
    readonly property color green:  "#5d743a"
    readonly property color cyan:   "#3a7348"
    readonly property color blue:   "#3c716a"
    readonly property color purple: "#993d69"
    readonly property color pink:   "#993d69"
}
