// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "frankenstein" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "frankenstein"
    readonly property string label:     "Frankenstein"
    readonly property string group:     "Horror"
    readonly property string glyph:     "⚡"
    readonly property bool   dark:      true

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#101815"
    readonly property color surface:      "#18261e"
    readonly property color fg:           "#d8f0d2"
    readonly property color muted:        "#9cc09b"
    readonly property color faint:        "#668567"
    readonly property color border:       "#31583e"
    readonly property color borderSubtle: "#213b2b"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#b6e35b"
    readonly property color accentHover: "#d4f47e"
    readonly property color code:        "#8ee38d"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#e05a5a"
    readonly property color orange: "#d98b45"
    readonly property color yellow: "#d8d95a"
    readonly property color green:  "#9ee35b"
    readonly property color cyan:   "#74d8c0"
    readonly property color blue:   "#78a9d8"
    readonly property color purple: "#aa88c9"
    readonly property color pink:   "#d8789e"
}
