// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "frankenstein-light" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "frankenstein-light"
    readonly property string label:     "Frankenstein Light"
    readonly property string group:     "Horror"
    readonly property string glyph:     "⚡"
    readonly property bool   dark:      false

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#ebf4f1"
    readonly property color surface:      "#dbebe2"
    readonly property color fg:           "#1d3d14"
    readonly property color muted:        "#4b8349"
    readonly property color faint:        "#69ab6b"
    readonly property color border:       "#a3ccb1"
    readonly property color borderSubtle: "#c4dece"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#527114"
    readonly property color accentHover: "#55710a"
    readonly property color code:        "#207b1e"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#b42222"
    readonly property color orange: "#a15d21"
    readonly property color yellow: "#6b6c19"
    readonly property color green:  "#477a15"
    readonly property color cyan:   "#227763"
    readonly property color blue:   "#306ca6"
    readonly property color purple: "#6d4393"
    readonly property color pink:   "#a6305f"
}
