// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "gameboy-light" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "gameboy-light"
    readonly property string label:     "Game Boy Light"
    readonly property string group:     "Retro"
    readonly property string glyph:     "▣"
    readonly property bool   dark:      false

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#e9f7ee"
    readonly property color surface:      "#d8eedf"
    readonly property color fg:           "#3e4c06"
    readonly property color muted:        "#97bc10"
    readonly property color faint:        "#c0ec27"
    readonly property color border:       "#9fd09f"
    readonly property color borderSubtle: "#c2e3bf"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#617015"
    readonly property color accentHover: "#67750f"
    readonly property color code:        "#62721d"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#617015"
    readonly property color orange: "#617015"
    readonly property color yellow: "#617015"
    readonly property color green:  "#617015"
    readonly property color cyan:   "#617015"
    readonly property color blue:   "#617015"
    readonly property color purple: "#617015"
    readonly property color pink:   "#617015"
}
