// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "gameboy" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "gameboy"
    readonly property string label:     "Game Boy"
    readonly property string group:     "Retro"
    readonly property string glyph:     "▣"
    readonly property bool   dark:      true

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#0f2818"
    readonly property color surface:      "#163420"
    readonly property color fg:           "#9bbc0f"
    readonly property color muted:        "#87a80e"
    readonly property color faint:        "#80a10e"
    readonly property color border:       "#306230"
    readonly property color borderSubtle: "#22461f"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#cfe36a"
    readonly property color accentHover: "#e2f08c"
    readonly property color code:        "#b8d24a"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#b7d428"
    readonly property color orange: "#c1db3f"
    readonly property color yellow: "#c8df55"
    readonly property color green:  "#cfe36a"
    readonly property color cyan:   "#d6e77f"
    readonly property color blue:   "#ddeb95"
    readonly property color purple: "#e4efaa"
    readonly property color pink:   "#ebf3c0"
}
