// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "gruvbox" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "gruvbox"
    readonly property string label:     "Gruvbox"
    readonly property string group:     "Editor"
    readonly property string glyph:     "◆"
    readonly property bool   dark:      true

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#282828"
    readonly property color surface:      "#32302f"
    readonly property color fg:           "#ebdbb2"
    readonly property color muted:        "#c4b393"
    readonly property color faint:        "#a89984"
    readonly property color border:       "#504945"
    readonly property color borderSubtle: "#3c3836"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#fabd2f"
    readonly property color accentHover: "#fed26b"
    readonly property color code:        "#b8bb26"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#fb4934"
    readonly property color orange: "#fe8019"
    readonly property color yellow: "#fabd2f"
    readonly property color green:  "#b8bb26"
    readonly property color cyan:   "#8ec07c"
    readonly property color blue:   "#83a598"
    readonly property color purple: "#d3869b"
    readonly property color pink:   "#d3869b"
}
