// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "gruvbox-light" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "gruvbox-light"
    readonly property string label:     "Gruvbox Light"
    readonly property string group:     "Editor"
    readonly property string glyph:     "◆"
    readonly property bool   dark:      false

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#f4ebeb"
    readonly property color surface:      "#ebe0db"
    readonly property color fg:           "#413311"
    readonly property color muted:        "#846f48"
    readonly property color faint:        "#ab8f69"
    readonly property color border:       "#ccb2a4"
    readonly property color borderSubtle: "#decdc4"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#866109"
    readonly property color accentHover: "#866009"
    readonly property color code:        "#6c6e17"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#c9210d"
    readonly property color orange: "#a34f0b"
    readonly property color yellow: "#866109"
    readonly property color green:  "#6c6e16"
    readonly property color cyan:   "#487539"
    readonly property color blue:   "#3e6f5c"
    readonly property color purple: "#9d3954"
    readonly property color pink:   "#9d3954"
}
