// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "kanagawa" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "kanagawa"
    readonly property string label:     "Kanagawa"
    readonly property string group:     "Modern"
    readonly property string glyph:     "◭"
    readonly property bool   dark:      true

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#1f1f28"
    readonly property color surface:      "#16161d"
    readonly property color fg:           "#dcd7ba"
    readonly property color muted:        "#c8c093"
    readonly property color faint:        "#727169"
    readonly property color border:       "#363646"
    readonly property color borderSubtle: "#2a2a37"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#957fb8"
    readonly property color accentHover: "#ab97cc"
    readonly property color code:        "#98bb6c"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#c34043"
    readonly property color orange: "#ffa066"
    readonly property color yellow: "#e6c384"
    readonly property color green:  "#98bb6c"
    readonly property color cyan:   "#6a9589"
    readonly property color blue:   "#7e9cd8"
    readonly property color purple: "#957fb8"
    readonly property color pink:   "#d27e99"
}
