// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "kanagawa-lotus" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "kanagawa-lotus"
    readonly property string label:     "Kanagawa Light"
    readonly property string group:     "Modern"
    readonly property string glyph:     "◭"
    readonly property bool   dark:      false

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#ebebf4"
    readonly property color surface:      "#dbdbeb"
    readonly property color fg:           "#36321b"
    readonly property color muted:        "#877d45"
    readonly property color faint:        "#aba369"
    readonly property color border:       "#a4a4cc"
    readonly property color borderSubtle: "#c4c4de"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#5f4983"
    readonly property color accentHover: "#4b366e"
    readonly property color code:        "#557033"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#a33336"
    readonly property color orange: "#ac480b"
    readonly property color yellow: "#88611b"
    readonly property color green:  "#556f34"
    readonly property color cyan:   "#3e6f61"
    readonly property color blue:   "#3258a4"
    readonly property color purple: "#644c8a"
    readonly property color pink:   "#9f3759"
}
