// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "light" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "light"
    readonly property string label:     "Light"
    readonly property string group:     "Light & print"
    readonly property string glyph:     "☀"
    readonly property bool   dark:      false

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#fffbeb"
    readonly property color surface:      "#f4f0df"
    readonly property color fg:           "#1f1f1f"
    readonly property color muted:        "#6c664b"
    readonly property color faint:        "#6c664b"
    readonly property color border:       "#cfcfde"
    readonly property color borderSubtle: "#e4dfcf"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#644ac9"
    readonly property color accentHover: "#4f36ad"
    readonly property color code:        "#14710a"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#b13535"
    readonly property color orange: "#b16f35"
    readonly property color yellow: "#b19c35"
    readonly property color green:  "#35b149"
    readonly property color cyan:   "#35b1b1"
    readonly property color blue:   "#3568b1"
    readonly property color purple: "#7735b1"
    readonly property color pink:   "#b13583"
}
