// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "lunarcore" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "lunarcore"
    readonly property string label:     "Lunarcore"
    readonly property string group:     "Core"
    readonly property string glyph:     "⏾"
    readonly property bool   dark:      true

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#060a14"
    readonly property color surface:      "#0d1526"
    readonly property color fg:           "#e6f0ff"
    readonly property color muted:        "#9fb2cc"
    readonly property color faint:        "#6c809e"
    readonly property color border:       "#24344d"
    readonly property color borderSubtle: "#141f30"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#7fe3ff"
    readonly property color accentHover: "#a6ecff"
    readonly property color code:        "#7ee787"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#f47b7b"
    readonly property color orange: "#f4b47b"
    readonly property color yellow: "#f4e07b"
    readonly property color green:  "#7bf48f"
    readonly property color cyan:   "#7bf4f4"
    readonly property color blue:   "#7badf4"
    readonly property color purple: "#bc7bf4"
    readonly property color pink:   "#f47bc8"
}
