// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "material-light" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "material-light"
    readonly property string label:     "Material Light"
    readonly property string group:     "Editor"
    readonly property string glyph:     "⬗"
    readonly property bool   dark:      false

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#f4ebeb"
    readonly property color surface:      "#ebdbdb"
    readonly property color fg:           "#054d4d"
    readonly property color muted:        "#497083"
    readonly property color faint:        "#ab6969"
    readonly property color border:       "#cca4a4"
    readonly property color borderSubtle: "#dec4c4"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#7421ab"
    readonly property color accentHover: "#5f1192"
    readonly property color code:        "#4b6e17"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#c2141e"
    readonly property color orange: "#c0350c"
    readonly property color yellow: "#906109"
    readonly property color green:  "#4a6e16"
    readonly property color cyan:   "#0a7099"
    readonly property color blue:   "#0d49c9"
    readonly property color purple: "#7a23b4"
    readonly property color pink:   "#c2141e"
}
