// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "material" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "material"
    readonly property string label:     "Material"
    readonly property string group:     "Editor"
    readonly property string glyph:     "⬗"
    readonly property bool   dark:      true

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#212121"
    readonly property color surface:      "#1a1a1a"
    readonly property color fg:           "#eeffff"
    readonly property color muted:        "#b0bec5"
    readonly property color faint:        "#545454"
    readonly property color border:       "#2f2f2f"
    readonly property color borderSubtle: "#272727"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#c792ea"
    readonly property color accentHover: "#d7a9f5"
    readonly property color code:        "#c3e88d"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#f07178"
    readonly property color orange: "#f78c6c"
    readonly property color yellow: "#ffcb6b"
    readonly property color green:  "#c3e88d"
    readonly property color cyan:   "#89ddff"
    readonly property color blue:   "#82aaff"
    readonly property color purple: "#c792ea"
    readonly property color pink:   "#f07178"
}
