// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "matrix" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "matrix"
    readonly property string label:     "Matrix"
    readonly property string group:     "Terminal"
    readonly property string glyph:     "⌁"
    readonly property bool   dark:      true

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#000500"
    readonly property color surface:      "#040c04"
    readonly property color fg:           "#3bff72"
    readonly property color muted:        "#26c651"
    readonly property color faint:        "#199a3c"
    readonly property color border:       "#0f4a1e"
    readonly property color borderSubtle: "#082e13"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#86ffab"
    readonly property color accentHover: "#b8ffce"
    readonly property color code:        "#c2ff64"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#2fee6a"
    readonly property color orange: "#4cf07e"
    readonly property color yellow: "#63f28f"
    readonly property color green:  "#7bf4a0"
    readonly property color cyan:   "#92f6b1"
    readonly property color blue:   "#aaf8c2"
    readonly property color purple: "#c2fad3"
    readonly property color pink:   "#d9fce4"
}
