// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "matrix-light" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "matrix-light"
    readonly property string label:     "Matrix Light"
    readonly property string group:     "Terminal"
    readonly property string glyph:     "⌁"
    readonly property bool   dark:      false

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#e2fde2"
    readonly property color surface:      "#d5f1d5"
    readonly property color fg:           "#054d19"
    readonly property color muted:        "#21ab46"
    readonly property color faint:        "#35de63"
    readonly property color border:       "#88e7a0"
    readonly property color borderSubtle: "#b1f1c4"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#087d2c"
    readonly property color accentHover: "#087c2c"
    readonly property color code:        "#4f7d08"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#0a7b2d"
    readonly property color orange: "#0b7b2d"
    readonly property color yellow: "#0a7b2d"
    readonly property color green:  "#0a7b2d"
    readonly property color cyan:   "#0a7b2d"
    readonly property color blue:   "#0a7b2d"
    readonly property color purple: "#0a7b2c"
    readonly property color pink:   "#0a7b2d"
}
