// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "monokai" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "monokai"
    readonly property string label:     "Monokai"
    readonly property string group:     "Editor"
    readonly property string glyph:     "✱"
    readonly property bool   dark:      true

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#272822"
    readonly property color surface:      "#1e1f1c"
    readonly property color fg:           "#f8f8f2"
    readonly property color muted:        "#b8b8a8"
    readonly property color faint:        "#75715e"
    readonly property color border:       "#3e3d32"
    readonly property color borderSubtle: "#2f2f28"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#f92672"
    readonly property color accentHover: "#ff4d8c"
    readonly property color code:        "#a6e22e"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#f92672"
    readonly property color orange: "#fd971f"
    readonly property color yellow: "#e6db74"
    readonly property color green:  "#a6e22e"
    readonly property color cyan:   "#66d9ef"
    readonly property color blue:   "#66d9ef"
    readonly property color purple: "#ae81ff"
    readonly property color pink:   "#f92672"
}
