// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "monokai-light" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "monokai-light"
    readonly property string label:     "Monokai Light"
    readonly property string group:     "Editor"
    readonly property string glyph:     "✱"
    readonly property bool   dark:      false

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#f3f4eb"
    readonly property color surface:      "#e6ebdb"
    readonly property color fg:           "#35351d"
    readonly property color muted:        "#838349"
    readonly property color faint:        "#ab9f69"
    readonly property color border:       "#ccc8a4"
    readonly property color borderSubtle: "#dedec4"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#c00c4d"
    readonly property color accentHover: "#990a3d"
    readonly property color code:        "#537410"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#c90d51"
    readonly property color orange: "#a35d0b"
    readonly property color yellow: "#796f16"
    readonly property color green:  "#537410"
    readonly property color cyan:   "#0e778b"
    readonly property color blue:   "#0e778b"
    readonly property color purple: "#500dc9"
    readonly property color pink:   "#c90d51"
}
