// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "mummy-light" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "mummy-light"
    readonly property string label:     "Mummy Light"
    readonly property string group:     "Horror"
    readonly property string glyph:     "𓂀"
    readonly property bool   dark:      false

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#f5f1ea"
    readonly property color surface:      "#ebe4db"
    readonly property color fg:           "#413211"
    readonly property color muted:        "#876f45"
    readonly property color faint:        "#ab9169"
    readonly property color border:       "#d6bc99"
    readonly property color borderSubtle: "#e3d2bf"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#8c6821"
    readonly property color accentHover: "#896310"
    readonly property color code:        "#637029"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#a54e31"
    readonly property color orange: "#9e5e23"
    readonly property color yellow: "#816618"
    readonly property color green:  "#616e35"
    readonly property color cyan:   "#3a7366"
    readonly property color blue:   "#4d6989"
    readonly property color purple: "#894d7f"
    readonly property color pink:   "#954441"
}
