// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "mummy" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "mummy"
    readonly property string label:     "Mummy"
    readonly property string group:     "Horror"
    readonly property string glyph:     "𓂀"
    readonly property bool   dark:      true

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#19140c"
    readonly property color surface:      "#282016"
    readonly property color fg:           "#ead7ad"
    readonly property color muted:        "#b69d70"
    readonly property color faint:        "#806b49"
    readonly property color border:       "#5d4525"
    readonly property color borderSubtle: "#3d2d1b"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#d6a84f"
    readonly property color accentHover: "#efc875"
    readonly property color code:        "#b7c86a"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#c86645"
    readonly property color orange: "#d58a45"
    readonly property color yellow: "#e0bd59"
    readonly property color green:  "#9caf59"
    readonly property color cyan:   "#6eb6a5"
    readonly property color blue:   "#718eaf"
    readonly property color purple: "#a47c9d"
    readonly property color pink:   "#c47a77"
}
