// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "nes-light" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "nes-light"
    readonly property string label:     "8-Bit Light"
    readonly property string group:     "Retro"
    readonly property string glyph:     "✜"
    readonly property bool   dark:      false

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#ebebf4"
    readonly property color surface:      "#dadaeb"
    readonly property color fg:           "#1a1a37"
    readonly property color muted:        "#494983"
    readonly property color faint:        "#6969ab"
    readonly property color border:       "#a2a2ce"
    readonly property color borderSubtle: "#c2c2e0"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#0c4dc0"
    readonly property color accentHover: "#0a3d99"
    readonly property color code:        "#407722"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#c61010"
    readonly property color orange: "#a0510d"
    readonly property color yellow: "#7b680a"
    readonly property color green:  "#0a7b1d"
    readonly property color cyan:   "#097171"
    readonly property color blue:   "#105cc6"
    readonly property color purple: "#7210c6"
    readonly property color pink:   "#c61083"
}
