// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "nes" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "nes"
    readonly property string label:     "8-Bit"
    readonly property string group:     "Retro"
    readonly property string glyph:     "✜"
    readonly property bool   dark:      true

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#0d0d17"
    readonly property color surface:      "#17172b"
    readonly property color fg:           "#e8e8f4"
    readonly property color muted:        "#a6a6c8"
    readonly property color faint:        "#7d7dac"
    readonly property color border:       "#38386a"
    readonly property color borderSubtle: "#202040"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#6ea2ff"
    readonly property color accentHover: "#97bcff"
    readonly property color code:        "#84d05a"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#f47979"
    readonly property color orange: "#f4b279"
    readonly property color yellow: "#f4e079"
    readonly property color green:  "#79f48d"
    readonly property color cyan:   "#79f4f4"
    readonly property color blue:   "#79acf4"
    readonly property color purple: "#bb79f4"
    readonly property color pink:   "#f479c7"
}
