// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "nord" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "nord"
    readonly property string label:     "Nord"
    readonly property string group:     "Editor"
    readonly property string glyph:     "❄"
    readonly property bool   dark:      true

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#2e3440"
    readonly property color surface:      "#3b4252"
    readonly property color fg:           "#eceff4"
    readonly property color muted:        "#d8dee9"
    readonly property color faint:        "#aab3c5"
    readonly property color border:       "#4c566a"
    readonly property color borderSubtle: "#434c5e"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#88c0d0"
    readonly property color accentHover: "#a6d3df"
    readonly property color code:        "#a3be8c"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#bf616a"
    readonly property color orange: "#d08770"
    readonly property color yellow: "#ebcb8b"
    readonly property color green:  "#a3be8c"
    readonly property color cyan:   "#88c0d0"
    readonly property color blue:   "#81a1c1"
    readonly property color purple: "#b48ead"
    readonly property color pink:   "#b48ead"
}
