// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "nord-light" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "nord-light"
    readonly property string label:     "Nord Light"
    readonly property string group:     "Editor"
    readonly property string glyph:     "❄"
    readonly property bool   dark:      false

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#ebeef4"
    readonly property color surface:      "#dbe0eb"
    readonly property color fg:           "#1d2634"
    readonly property color muted:        "#495e83"
    readonly property color faint:        "#697fab"
    readonly property color border:       "#a4b1cc"
    readonly property color borderSubtle: "#c4cdde"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#347283"
    readonly property color accentHover: "#2b6878"
    readonly property color code:        "#556f3e"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#983e46"
    readonly property color orange: "#a14f35"
    readonly property color yellow: "#8b6418"
    readonly property color green:  "#556f3e"
    readonly property color cyan:   "#347284"
    readonly property color blue:   "#476b90"
    readonly property color purple: "#894d7e"
    readonly property color pink:   "#894d7e"
}
