// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "one-light" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "one-light"
    readonly property string label:     "One Light"
    readonly property string group:     "Editor"
    readonly property string glyph:     "⬡"
    readonly property bool   dark:      false

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#fafafa"
    readonly property color surface:      "#eaeaeb"
    readonly property color fg:           "#383a42"
    readonly property color muted:        "#696c77"
    readonly property color faint:        "#a0a1a7"
    readonly property color border:       "#d3d3d4"
    readonly property color borderSubtle: "#e5e5e6"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#a626a4"
    readonly property color accentHover: "#8b1f89"
    readonly property color code:        "#50a14f"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#e45649"
    readonly property color orange: "#c18401"
    readonly property color yellow: "#c18401"
    readonly property color green:  "#50a14f"
    readonly property color cyan:   "#0184bc"
    readonly property color blue:   "#4078f2"
    readonly property color purple: "#a626a4"
    readonly property color pink:   "#e45649"
}
