// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "one-dark" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "one-dark"
    readonly property string label:     "One Dark"
    readonly property string group:     "Editor"
    readonly property string glyph:     "⬢"
    readonly property bool   dark:      true

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#282c34"
    readonly property color surface:      "#21252b"
    readonly property color fg:           "#abb2bf"
    readonly property color muted:        "#8b92a0"
    readonly property color faint:        "#5c6370"
    readonly property color border:       "#3b4048"
    readonly property color borderSubtle: "#2f333a"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#c678dd"
    readonly property color accentHover: "#d68fe8"
    readonly property color code:        "#98c379"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#e06c75"
    readonly property color orange: "#d19a66"
    readonly property color yellow: "#e5c07b"
    readonly property color green:  "#98c379"
    readonly property color cyan:   "#56b6c2"
    readonly property color blue:   "#61afef"
    readonly property color purple: "#c678dd"
    readonly property color pink:   "#e06c75"
}
