// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "paper" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "paper"
    readonly property string label:     "Paper"
    readonly property string group:     "Light & print"
    readonly property string glyph:     "¶"
    readonly property bool   dark:      false

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#f4f1e8"
    readonly property color surface:      "#ebe7da"
    readonly property color fg:           "#1c1a15"
    readonly property color muted:        "#4f4a3d"
    readonly property color faint:        "#6e6759"
    readonly property color border:       "#ccc5b2"
    readonly property color borderSubtle: "#ddd7c6"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#8a2f13"
    readonly property color accentHover: "#6b2410"
    readonly property color code:        "#2f5d3a"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#8a1313"
    readonly property color orange: "#8a4b13"
    readonly property color yellow: "#8a7613"
    readonly property color green:  "#138a27"
    readonly property color cyan:   "#138a8a"
    readonly property color blue:   "#13458a"
    readonly property color purple: "#52138a"
    readonly property color pink:   "#8a135e"
}
