// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "phantom" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "phantom"
    readonly property string label:     "Phantom"
    readonly property string group:     "Horror"
    readonly property string glyph:     "◌"
    readonly property bool   dark:      true

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#12101b"
    readonly property color surface:      "#211b30"
    readonly property color fg:           "#eee6ff"
    readonly property color muted:        "#b7a9cf"
    readonly property color faint:        "#79698f"
    readonly property color border:       "#4b3b65"
    readonly property color borderSubtle: "#302640"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#d6b3ff"
    readonly property color accentHover: "#ead5ff"
    readonly property color code:        "#8ff0d0"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#e16c91"
    readonly property color orange: "#d99a69"
    readonly property color yellow: "#dbc979"
    readonly property color green:  "#86cf9d"
    readonly property color cyan:   "#79d4d4"
    readonly property color blue:   "#8da8e0"
    readonly property color purple: "#c2a0ef"
    readonly property color pink:   "#df91c0"
}
