// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "phantom-light" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "phantom-light"
    readonly property string label:     "Phantom Light"
    readonly property string group:     "Horror"
    readonly property string glyph:     "◌"
    readonly property bool   dark:      false

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#edebf4"
    readonly property color surface:      "#e0dbeb"
    readonly property color fg:           "#1c054d"
    readonly property color muted:        "#5e4983"
    readonly property color faint:        "#8569ab"
    readonly property color border:       "#b3a4cc"
    readonly property color borderSubtle: "#cec4de"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#5f0cc0"
    readonly property color accentHover: "#520a99"
    readonly property color code:        "#107554"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#b22451"
    readonly property color orange: "#9b5a27"
    readonly property color yellow: "#796820"
    readonly property color green:  "#2f7545"
    readonly property color cyan:   "#257474"
    readonly property color blue:   "#2e56a8"
    readonly property color purple: "#601fb7"
    readonly property color pink:   "#a63077"
}
