// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "rose-pine-dawn" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "rose-pine-dawn"
    readonly property string label:     "Rosé Pine Light"
    readonly property string group:     "Modern"
    readonly property string glyph:     "✿"
    readonly property bool   dark:      false

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#edebf4"
    readonly property color surface:      "#dddbeb"
    readonly property color fg:           "#18143d"
    readonly property color muted:        "#514983"
    readonly property color faint:        "#7269ab"
    readonly property color border:       "#a9a4cc"
    readonly property color borderSubtle: "#c7c4de"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#612ca0"
    readonly property color accentHover: "#4b158e"
    readonly property color code:        "#31717c"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#bc1a48"
    readonly property color orange: "#905809"
    readonly property color yellow: "#905809"
    readonly property color green:  "#2f6e89"
    readonly property color cyan:   "#31717d"
    readonly property color blue:   "#2f6e89"
    readonly property color purple: "#652ea8"
    readonly property color pink:   "#a63530"
}
