// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "rose-pine" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "rose-pine"
    readonly property string label:     "Rosé Pine"
    readonly property string group:     "Modern"
    readonly property string glyph:     "✿"
    readonly property bool   dark:      true

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#191724"
    readonly property color surface:      "#1f1d2e"
    readonly property color fg:           "#e0def4"
    readonly property color muted:        "#908caa"
    readonly property color faint:        "#6e6a86"
    readonly property color border:       "#26233a"
    readonly property color borderSubtle: "#211f30"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#c4a7e7"
    readonly property color accentHover: "#d6bdf5"
    readonly property color code:        "#9ccfd8"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#eb6f92"
    readonly property color orange: "#f6c177"
    readonly property color yellow: "#f6c177"
    readonly property color green:  "#31748f"
    readonly property color cyan:   "#9ccfd8"
    readonly property color blue:   "#31748f"
    readonly property color purple: "#c4a7e7"
    readonly property color pink:   "#ebbcba"
}
