// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "sepia" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "sepia"
    readonly property string label:     "Steampunk"
    readonly property string group:     "Light & print"
    readonly property string glyph:     "⚙"
    readonly property bool   dark:      true

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#241a10"
    readonly property color surface:      "#2f2415"
    readonly property color fg:           "#ecd9b0"
    readonly property color muted:        "#c6ac7c"
    readonly property color faint:        "#a58e60"
    readonly property color border:       "#574227"
    readonly property color borderSubtle: "#3a2c19"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#e0b154"
    readonly property color accentHover: "#eec87e"
    readonly property color code:        "#aeb87e"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#e05454"
    readonly property color orange: "#e09554"
    readonly property color yellow: "#e0c954"
    readonly property color green:  "#54e06b"
    readonly property color cyan:   "#54e0e0"
    readonly property color blue:   "#548ee0"
    readonly property color purple: "#9f54e0"
    readonly property color pink:   "#e054ad"
}
