// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "solarized-light" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "solarized-light"
    readonly property string label:     "Solarized Light"
    readonly property string group:     "Editor"
    readonly property string glyph:     "◉"
    readonly property bool   dark:      false

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#e2f8fd"
    readonly property color surface:      "#ccf0fa"
    readonly property color fg:           "#1d3434"
    readonly property color muted:        "#497583"
    readonly property color faint:        "#6999ab"
    readonly property color border:       "#7edbf1"
    readonly property color borderSubtle: "#ace7f6"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#1f7a72"
    readonly property color accentHover: "#297a74"
    readonly property color code:        "#657308"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#b7211f"
    readonly property color orange: "#c14715"
    readonly property color yellow: "#866809"
    readonly property color green:  "#657307"
    readonly property color cyan:   "#1f7a72"
    readonly property color blue:   "#1f72ad"
    readonly property color purple: "#3d4399"
    readonly property color pink:   "#b02669"
}
