// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "solarcore" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "solarcore"
    readonly property string label:     "Solarcore"
    readonly property string group:     "Core"
    readonly property string glyph:     "✸"
    readonly property bool   dark:      false

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#f4f7ec"
    readonly property color surface:      "#e7efd6"
    readonly property color fg:           "#16261a"
    readonly property color muted:        "#3c5340"
    readonly property color faint:        "#4f6650"
    readonly property color border:       "#c6d6ac"
    readonly property color borderSubtle: "#dbe6c6"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#2a6f34"
    readonly property color accentHover: "#1f5527"
    readonly property color code:        "#8a4b0a"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#6f2a2a"
    readonly property color orange: "#6f4a2a"
    readonly property color yellow: "#6f642a"
    readonly property color green:  "#2a6f35"
    readonly property color cyan:   "#2a6f6f"
    readonly property color blue:   "#2a476f"
    readonly property color purple: "#4f2a6f"
    readonly property color pink:   "#6f2a56"
}
