// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "solarized" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "solarized"
    readonly property string label:     "Solarized"
    readonly property string group:     "Editor"
    readonly property string glyph:     "◉"
    readonly property bool   dark:      true

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#002b36"
    readonly property color surface:      "#073642"
    readonly property color fg:           "#93a1a1"
    readonly property color muted:        "#8b9ba0"
    readonly property color faint:        "#8a9ba1"
    readonly property color border:       "#0a4b5a"
    readonly property color borderSubtle: "#073642"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#2ca99f"
    readonly property color accentHover: "#4cc2b9"
    readonly property color code:        "#8da200"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#dc322f"
    readonly property color orange: "#cb4b16"
    readonly property color yellow: "#b58900"
    readonly property color green:  "#859900"
    readonly property color cyan:   "#2aa198"
    readonly property color blue:   "#268bd2"
    readonly property color purple: "#6c71c4"
    readonly property color pink:   "#d33682"
}
