// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "synthwave-light" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "synthwave-light"
    readonly property string label:     "Synthwave Light"
    readonly property string group:     "Neon"
    readonly property string glyph:     "▹"
    readonly property bool   dark:      false

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#eee6f9"
    readonly property color surface:      "#e0d2f4"
    readonly property color fg:           "#30054d"
    readonly property color muted:        "#712ca0"
    readonly property color faint:        "#9159bb"
    readonly property color border:       "#b396d9"
    readonly property color borderSubtle: "#ccb9e9"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#c00c5e"
    readonly property color accentHover: "#990a4d"
    readonly property color code:        "#087372"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#c61010"
    readonly property color orange: "#a0510d"
    readonly property color yellow: "#7b670a"
    readonly property color green:  "#09711b"
    readonly property color cyan:   "#097171"
    readonly property color blue:   "#105cc6"
    readonly property color purple: "#7210c6"
    readonly property color pink:   "#c61083"
}
