// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "synthwave" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "synthwave"
    readonly property string label:     "Synthwave"
    readonly property string group:     "Neon"
    readonly property string glyph:     "▹"
    readonly property bool   dark:      true

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#1a0b2e"
    readonly property color surface:      "#241040"
    readonly property color fg:           "#f5e6ff"
    readonly property color muted:        "#c79ce4"
    readonly property color faint:        "#a06fc4"
    readonly property color border:       "#4a2a75"
    readonly property color borderSubtle: "#301a52"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#ff5fa8"
    readonly property color accentHover: "#ff8cc2"
    readonly property color code:        "#36f9f6"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#f36b6b"
    readonly property color orange: "#f3aa6b"
    readonly property color yellow: "#f3dc6b"
    readonly property color green:  "#6bf382"
    readonly property color cyan:   "#6bf3f3"
    readonly property color blue:   "#6ba4f3"
    readonly property color purple: "#b46bf3"
    readonly property color pink:   "#f36bc1"
}
