// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "teletext" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "teletext"
    readonly property string label:     "Teletext"
    readonly property string group:     "Terminal"
    readonly property string glyph:     "⌗"
    readonly property bool   dark:      true

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#000000"
    readonly property color surface:      "#101010"
    readonly property color fg:           "#ffffff"
    readonly property color muted:        "#cfcfcf"
    readonly property color faint:        "#9a9a9a"
    readonly property color border:       "#333333"
    readonly property color borderSubtle: "#1c1c1c"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#ffe800"
    readonly property color accentHover: "#fff45c"
    readonly property color code:        "#22ff9a"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#b8a90f"
    readonly property color orange: "#d4c311"
    readonly property color yellow: "#ecd813"
    readonly property color green:  "#eedc2b"
    readonly property color cyan:   "#f0e042"
    readonly property color blue:   "#f2e45a"
    readonly property color purple: "#f4e871"
    readonly property color pink:   "#f5ec89"
}
