// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "teletext-light" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "teletext-light"
    readonly property string label:     "Teletext Light"
    readonly property string group:     "Terminal"
    readonly property string glyph:     "⌗"
    readonly property bool   dark:      false

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#f4ebeb"
    readonly property color surface:      "#ebdbdb"
    readonly property color fg:           "#341d1d"
    readonly property color muted:        "#834949"
    readonly property color faint:        "#ab6969"
    readonly property color border:       "#cca4a4"
    readonly property color borderSubtle: "#dec4c4"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#736907"
    readonly property color accentHover: "#736c08"
    readonly property color code:        "#087342"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#716809"
    readonly property color orange: "#716809"
    readonly property color yellow: "#716809"
    readonly property color green:  "#716809"
    readonly property color cyan:   "#716809"
    readonly property color blue:   "#716809"
    readonly property color purple: "#726809"
    readonly property color pink:   "#71680a"
}
