// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "tokyo-night" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "tokyo-night"
    readonly property string label:     "Tokyo Night"
    readonly property string group:     "Modern"
    readonly property string glyph:     "✺"
    readonly property bool   dark:      true

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#1a1b26"
    readonly property color surface:      "#16161e"
    readonly property color fg:           "#c0caf5"
    readonly property color muted:        "#a9b1d6"
    readonly property color faint:        "#565f89"
    readonly property color border:       "#292e42"
    readonly property color borderSubtle: "#1f2233"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#bb9af7"
    readonly property color accentHover: "#cbb0ff"
    readonly property color code:        "#9ece6a"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#f7768e"
    readonly property color orange: "#ff9e64"
    readonly property color yellow: "#e0af68"
    readonly property color green:  "#9ece6a"
    readonly property color cyan:   "#7dcfff"
    readonly property color blue:   "#7aa2f7"
    readonly property color purple: "#bb9af7"
    readonly property color pink:   "#ff75a0"
}
