// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "tokyo-night-light" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "tokyo-night-light"
    readonly property string label:     "Tokyo Night Light"
    readonly property string group:     "Modern"
    readonly property string glyph:     "✺"
    readonly property bool   dark:      false

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#ebecf4"
    readonly property color surface:      "#dbdbeb"
    readonly property color fg:           "#0b1646"
    readonly property color muted:        "#424f8a"
    readonly property color faint:        "#6974ab"
    readonly property color border:       "#a4accc"
    readonly property color borderSubtle: "#c4c8de"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#4d0fbd"
    readonly property color accentHover: "#3b0a99"
    readonly property color code:        "#4e7326"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#c90d30"
    readonly property color orange: "#ac470b"
    readonly property color yellow: "#90611d"
    readonly property color green:  "#4e7326"
    readonly property color cyan:   "#0b6ba3"
    readonly property color blue:   "#0d49c9"
    readonly property color purple: "#5110c6"
    readonly property color pink:   "#c90d48"
}
