// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "tomorrow-night" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "tomorrow-night"
    readonly property string label:     "Tomorrow Night"
    readonly property string group:     "Editor"
    readonly property string glyph:     "✧"
    readonly property bool   dark:      true

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#1d1f21"
    readonly property color surface:      "#282a2e"
    readonly property color fg:           "#c5c8c6"
    readonly property color muted:        "#a3a6a4"
    readonly property color faint:        "#969896"
    readonly property color border:       "#373b41"
    readonly property color borderSubtle: "#2a2d30"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#b294bb"
    readonly property color accentHover: "#c4a8cb"
    readonly property color code:        "#b5bd68"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#cc6666"
    readonly property color orange: "#de935f"
    readonly property color yellow: "#f0c674"
    readonly property color green:  "#b5bd68"
    readonly property color cyan:   "#8abeb7"
    readonly property color blue:   "#81a2be"
    readonly property color purple: "#b294bb"
    readonly property color pink:   "#cc6666"
}
