// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "tomorrow-day" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "tomorrow-day"
    readonly property string label:     "Tomorrow Night Light"
    readonly property string group:     "Editor"
    readonly property string glyph:     "✧"
    readonly property bool   dark:      false

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#ebf0f4"
    readonly property color surface:      "#dbe0eb"
    readonly property color fg:           "#1d3425"
    readonly property color muted:        "#49835c"
    readonly property color faint:        "#69ab69"
    readonly property color border:       "#a4b4cc"
    readonly property color borderSubtle: "#c4d1de"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#754983"
    readonly property color accentHover: "#5f3b68"
    readonly property color code:        "#656b2f"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#a13636"
    readonly property color orange: "#a15521"
    readonly property color yellow: "#8a610f"
    readonly property color green:  "#656b2e"
    readonly property color cyan:   "#41766f"
    readonly property color blue:   "#496e8d"
    readonly property color purple: "#7b4d89"
    readonly property color pink:   "#a13636"
}
