// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "tron" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "tron"
    readonly property string label:     "Tron"
    readonly property string group:     "Neon"
    readonly property string glyph:     "⊞"
    readonly property bool   dark:      true

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#030a0f"
    readonly property color surface:      "#08161f"
    readonly property color fg:           "#d6f4ff"
    readonly property color muted:        "#8fc9e0"
    readonly property color faint:        "#5f9bb6"
    readonly property color border:       "#124a5e"
    readonly property color borderSubtle: "#0a2f3d"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#6ee2ff"
    readonly property color accentHover: "#a2eeff"
    readonly property color code:        "#ffa23e"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#f47979"
    readonly property color orange: "#f4b279"
    readonly property color yellow: "#f4e079"
    readonly property color green:  "#79f48d"
    readonly property color cyan:   "#79f4f4"
    readonly property color blue:   "#79acf4"
    readonly property color purple: "#bb79f4"
    readonly property color pink:   "#f479c7"
}
