// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "tron-light" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "tron-light"
    readonly property string label:     "Tron Light"
    readonly property string group:     "Neon"
    readonly property string glyph:     "⊞"
    readonly property bool   dark:      false

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#e6f1fa"
    readonly property color surface:      "#d2e7f3"
    readonly property color fg:           "#05394d"
    readonly property color muted:        "#2c7fa0"
    readonly property color faint:        "#5e9ab5"
    readonly property color border:       "#87cfe8"
    readonly property color borderSubtle: "#b0e0f2"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#097590"
    readonly property color accentHover: "#097790"
    readonly property color code:        "#a3590b"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#c61010"
    readonly property color orange: "#aa560e"
    readonly property color yellow: "#7b680a"
    readonly property color green:  "#0a7b1d"
    readonly property color cyan:   "#097171"
    readonly property color blue:   "#105cc6"
    readonly property color purple: "#7210c6"
    readonly property color pink:   "#c61083"
}
