// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "vaporwave" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "vaporwave"
    readonly property string label:     "Vaporwave"
    readonly property string group:     "Neon"
    readonly property string glyph:     "▧"
    readonly property bool   dark:      true

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#241734"
    readonly property color surface:      "#2f2044"
    readonly property color fg:           "#ffe6f7"
    readonly property color muted:        "#dbabe6"
    readonly property color faint:        "#b17fc9"
    readonly property color border:       "#4d3568"
    readonly property color borderSubtle: "#362548"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#3fd8ff"
    readonly property color accentHover: "#77e6ff"
    readonly property color code:        "#ff8ad8"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#f14d4d"
    readonly property color orange: "#f19a4d"
    readonly property color yellow: "#f1d54d"
    readonly property color green:  "#4df169"
    readonly property color cyan:   "#4df1f1"
    readonly property color blue:   "#4d91f1"
    readonly property color purple: "#a44df1"
    readonly property color pink:   "#f14db5"
}
