// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "vaporwave-light" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "vaporwave-light"
    readonly property string label:     "Vaporwave Light"
    readonly property string group:     "Neon"
    readonly property string glyph:     "▧"
    readonly property bool   dark:      false

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#efeaf6"
    readonly property color surface:      "#e1d9ed"
    readonly property color fg:           "#4d0536"
    readonly property color muted:        "#892f9d"
    readonly property color faint:        "#9a5ab9"
    readonly property color border:       "#b6a0cf"
    readonly property color borderSubtle: "#d1c2e0"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#097490"
    readonly property color accentHover: "#096f86"
    readonly property color code:        "#b60c7d"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#c71010"
    readonly property color orange: "#a1530d"
    readonly property color yellow: "#7b680a"
    readonly property color green:  "#0a7b1d"
    readonly property color cyan:   "#097171"
    readonly property color blue:   "#105bc7"
    readonly property color purple: "#7110c7"
    readonly property color pink:   "#c71084"
}
