// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "werewolf-light" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "werewolf-light"
    readonly property string label:     "Werewolf Light"
    readonly property string group:     "Horror"
    readonly property string glyph:     "☾"
    readonly property bool   dark:      false

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#eaedf6"
    readonly property color surface:      "#d9e0ed"
    readonly property color fg:           "#14253e"
    readonly property color muted:        "#496183"
    readonly property color faint:        "#6982ab"
    readonly property color border:       "#9eb2d1"
    readonly property color borderSubtle: "#c0cde2"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#2754a5"
    readonly property color accentHover: "#1c4288"
    readonly property color code:        "#4a742f"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#a63040"
    readonly property color orange: "#915f31"
    readonly property color yellow: "#776622"
    readonly property color green:  "#4f703e"
    readonly property color cyan:   "#307173"
    readonly property color blue:   "#3464a3"
    readonly property color purple: "#604196"
    readonly property color pink:   "#924471"
}
