// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "werewolf" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "werewolf"
    readonly property string label:     "Werewolf"
    readonly property string group:     "Horror"
    readonly property string glyph:     "☾"
    readonly property bool   dark:      true

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#0c111c"
    readonly property color surface:      "#151d2c"
    readonly property color fg:           "#d7e2f2"
    readonly property color muted:        "#94a7c3"
    readonly property color faint:        "#5f718e"
    readonly property color border:       "#2d405e"
    readonly property color borderSubtle: "#1e2c42"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#9db8e8"
    readonly property color accentHover: "#bfd1f2"
    readonly property color code:        "#a6d08b"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#d26372"
    readonly property color orange: "#c9925f"
    readonly property color yellow: "#d8c477"
    readonly property color green:  "#91b77d"
    readonly property color cyan:   "#79c4c7"
    readonly property color blue:   "#719bd2"
    readonly property color purple: "#a992d0"
    readonly property color pink:   "#c888ad"
}
