// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "zenburn" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "zenburn"
    readonly property string label:     "Zenburn"
    readonly property string group:     "Editor"
    readonly property string glyph:     "⌾"
    readonly property bool   dark:      true

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#3f3f3f"
    readonly property color surface:      "#383838"
    readonly property color fg:           "#dcdccc"
    readonly property color muted:        "#b0b0a0"
    readonly property color faint:        "#7f9f7f"
    readonly property color border:       "#4f4f4f"
    readonly property color borderSubtle: "#464646"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#dc8cc3"
    readonly property color accentHover: "#e9a5d4"
    readonly property color code:        "#7f9f7f"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#cc9393"
    readonly property color orange: "#dfaf8f"
    readonly property color yellow: "#f0dfaf"
    readonly property color green:  "#7f9f7f"
    readonly property color cyan:   "#93e0e3"
    readonly property color blue:   "#8cd0d3"
    readonly property color purple: "#dc8cc3"
    readonly property color pink:   "#cc9393"
}
