// GENERATED by scripts/gen-themes.py from Theme/palettes.json -- do not edit.
// Edit the palette entry named "zenburn-light" and re-run the generator instead.

import QtQuick

QtObject {
    readonly property string themeName: "zenburn-light"
    readonly property string label:     "Zenburn Light"
    readonly property string group:     "Editor"
    readonly property string glyph:     "⌾"
    readonly property bool   dark:      false

    // ── Surface ──────────────────────────────────────────────
    readonly property color base:         "#f4ebeb"
    readonly property color surface:      "#ebdbdb"
    readonly property color fg:           "#34341d"
    readonly property color muted:        "#838349"
    readonly property color faint:        "#69ab69"
    readonly property color border:       "#cca4a4"
    readonly property color borderSubtle: "#dec4c4"

    // ── Accents ──────────────────────────────────────────────
    readonly property color accent:      "#9c307a"
    readonly property color accentHover: "#832065"
    readonly property color code:        "#427642"

    // ── Module ramp ──────────────────────────────────────────
    readonly property color red:    "#914545"
    readonly property color orange: "#9e5a2e"
    readonly property color yellow: "#816618"
    readonly property color green:  "#427642"
    readonly property color cyan:   "#1f767a"
    readonly property color blue:   "#2d7376"
    readonly property color purple: "#a43281"
    readonly property color pink:   "#914545"
}
